export const no_of_results_options = [
  {
    name: "top 100",
    value: "100",
  },
  {
    name: "top 200",
    value: "200",
  },
  {
    name: "top 300",
    value: "300",
  },
  {
    name: "top 500",
    value: "500",
  },
  {
    name: "top 1000",
    value: "1000",
  },
];

export const locations = [
  "Afghanistan",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Bhutan",
  "Bosnia-Herzegovina",
  "British Indian Ocean Territory",
  "Brunei",
  "Canada",
  "Central African Republic",
  "Chile",
  "China",
  "Columbia",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "East Germany",
  "Egypt",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "India",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Lithuania",
  "Malaysia",
  "Maldives",
  "Mali",
  "Mauritania",
  "Moldova",
  "Montenegro",
  "Morocco",
  "Myanmar (Burma)",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Philippines (Mindanao)",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of Korea",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "USA",
  "USA/Texas",
  "Uzbekistan",
  "Vatican City",
  "Vietnam",
  "Yemen",
];

let helper = locations.map((d) => ({
  name: d,
  value: d,
}));
export const locations_options = [
  { name: "All countries", value: "All countries" },
  ...helper,
];
console.log(locations_options);
